language: node_js
node_js:
  - 12
install:
  - npm i --no-optional
  - wget -O node_modules/swagger2openapi/schemas/openapi-3.0.json https://gist.githubusercontent.com/MikeRalphson/f8cc09fabf7372302c269532f55562bf/raw/3678521df7ebc95e31101a19bbbbbf50c25d829c/oaslax.json
script:
  - node --max-old-space-size=8192 scripts/collection.js validate -q --fix APIs/googleapis.com
deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./scripts/deploy.sh
    on:
      branch: master
  - provider: pages
    skip-cleanup: true
    local-dir: deploy
    repo: APIs-guru/openapi-directory-api
    fqdn: minff.github.io/mdl-catalog
    github-token: $GH_DEPLOY_TOKEN
    keep-history: false
    on:
      branch: master

