name: Reusable Build and Deploy API

# Author: @minff
# Issue : n/a
# Desc  : Reusable build and deploy workflow

on:
  workflow_call:
    inputs:
      api-repo:
        description: 'Repository for API hosting'
        type: string
        required: true
        default: 'MobiDataLab/mdl-catalog-api'
      api-repo-ref:
        description: 'Repository git ref for API source'
        type: string
        required: false
        default: 'refs/heads/main'
      cache-repo:
        description: 'External repository name for published specs as cache, in case specs are oudated'
        type: string
        required: false
      cache-repo-ref:
        description: 'External repository git ref for published specs as cache, in case specs are oudated'
        type: string
        required: false
        default: 'refs/heads/gh-pages'
      deployment-repo:
        description: 'Repository for deployment script'
        type: string
        required: false
        default: 'MobiDataLab/mdl-catalog-deployment'
      deployment-repo-ref:
        description: 'Repository git ref for deployment script'
        type: string
        required: false
        default: 'refs/heads/main'
      deploy-gh-pages:
        description: 'Set the flag to true to deploy to gh-pages'
        type: boolean
        required: false
        default: false
    secrets:
      DEPLOY_KEY:
        description: 'Deploy key to push to api-repo'
        required: false

env:
  NODE_OPTIONS: --max_old_space_size=8192
  API_PATH: ${{ github.workspace }}/mdl-catalog-api

concurrency:
  group: ${{ inputs.deploy-gh-pages && 'deploy-gh-pages' || format('build-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  build-deploy:
    name: ${{ inputs.deploy-gh-pages && 'Bulld and Deploy' || 'Build' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v3
    - name: Checkout deployment repo
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.deployment-repo }}
        ref: ${{ inputs.deployment-repo-ref }}
        path: mdl-catalog-deployment
    - name: Checkout api repo
      uses: actions/checkout@v3
      if: ${{ inputs.api-repo }}
      with:
        repository: ${{ inputs.api-repo }}
        ref: ${{ inputs.api-repo-ref }}
        path: mdl-catalog-api
    - name: Copy APIs
      if: ${{ inputs.api-repo }}
      run: |
        cp -r ./mdl-catalog-api/* ./mdl-catalog-deployment/
    - name: Checkout cache repo
      uses: actions/checkout@v3
      if: ${{ inputs.cache-repo }}
      with:
        repository: ${{ inputs.cache-repo }}
        ref: ${{ inputs.cache-repo-ref }}
        path: openapi-directory
    - name: Copy cache
      if: ${{ inputs.cache-repo }}
      run: |
        mkdir -p ./mdl-catalog-deployment/deploy/v2
        cp -r ./openapi-directory/v2/cache ./mdl-catalog-deployment/deploy/v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install deps
      run: npm i --no-optional
      working-directory: mdl-catalog-deployment
    - name: Validate API specs
      run: npm run test ./APIs/
      working-directory: mdl-catalog-deployment
    - name: Build deploy artifacts
      run: npm run deploy
      working-directory: mdl-catalog-deployment
    - name: Deploy to API repo 🚀
      uses: JamesIves/github-pages-deploy-action@4.0.0
      if: ${{ inputs.api-repo && inputs.deploy-gh-pages }}
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}
        repository-name: ${{ inputs.api-repo }}
        branch: gh-pages
        folder: mdl-catalog-deployment/deploy
        git-config-name: github-actions[bot]
        git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
        single-commit: true

