name: Deploy API

# Author: @minff
# Issue : n/a
# Desc  : This workflow runs a build on pushes to main and prs

# run this on push to main
on:
  push:
    branches: [main]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]

jobs:
  deploy-mobidatalab:
    uses: ./.github/workflows/base_deploy.yaml
    with:
      api-repo: mobidatalab/mdl-catalog-api
      cache-repo: APIs-guru/openapi-directory
    secrets:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

