name: Deploy API

# Author: @minff
# Issue : n/a
# Desc  : This workflow runs a build on pushes to main and prs

# run this on push to main
on:
  push:
    branches: [main]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]

jobs:
  deploy-sample:
    uses: minff/mdl-catalog-deployment/.github/workflows/base_deploy.yaml@mdl
    with:
      api-repo: minff/mdl-catalog-api
    secrets:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
  deploy-mobidatalab:
    uses: minff/mdl-catalog-deployment/.github/workflows/base_deploy.yaml@mdl
    with:
      api-repo: mobidatalab/mdl-catalog-api
    secrets:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY_MDL }}
