name: Deploy API

# Author: @minff
# Issue : n/a
# Desc  : This workflow runs a build on pushes to main and prs

on:
  # push:
  #   branches: [main]
  workflow_dispatch:


jobs:
  deploy-mobidatalab:
    uses: ./.github/workflows/base_deploy.yaml
    with:
      api-repo: MobiDataLab/mdl-catalog-api
      cache-repo: APIs-guru/openapi-directory
    secrets:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

